// <auto-generated />
using KraigsList.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace KraigsList.Data.Migrations
{
    [DbContext(typeof(KraigsListContext))]
    [Migration("20170919233323_AdInit")]
    partial class AdInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("KraigsList.Data.Ad", b =>
                {
                    b.Property<int>("AdId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ActiveId");

                    b.Property<int>("CategoryId");

                    b.Property<string>("City");

                    b.Property<string>("Description");

                    b.Property<string>("Email");

                    b.Property<string>("Phone");

                    b.Property<decimal>("Price");

                    b.Property<string>("State");

                    b.Property<string>("Street");

                    b.Property<DateTime>("Timestamp");

                    b.Property<string>("Title");

                    b.Property<int>("Zip");

                    b.HasKey("AdId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Ad");
                });

            modelBuilder.Entity("KraigsList.Data.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("KraigsList.Data.Ad", b =>
                {
                    b.HasOne("KraigsList.Data.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
